# Generated by Django 3.1.5 on 2021-02-23 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_auto_20210222_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Discount Code')),
                ('discount_type', models.CharField(choices=[('SHIPPING', 'SHIPPING'), ('ORDER', 'ORDER'), ('PRODUCT', 'PRODUCT')], default='ORDER', max_length=8, verbose_name='Discount Type')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Discount % (NB: 1 == 100%)')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
