# Generated by Django 3.1.5 on 2021-02-23 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210222_1126'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product (if applicable)'),
        ),
    ]
