# Generated by Django 3.1.5 on 2021-02-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20210216_1243'),
        ('discounts', '0002_auto_20210223_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='usage_frequency',
            field=models.CharField(choices=[('SINGLE_USE', 'SINGLE USE'), ('MULTI_USE', 'MULTI USE')], default='MULTI_USE', max_length=128, verbose_name='Usage Frequency'),
        ),
        migrations.AddField(
            model_name='discount',
            name='used_by_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order (applicable only for single use)'),
        ),
    ]
