# Generated by Django 3.1.5 on 2021-02-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20210216_1243'),
        ('discounts', '0003_auto_20210223_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_desc',
            field=models.CharField(default='The description', max_length=100, verbose_name='Discount Display Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='used_by_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order ID (applicable only for single use)'),
        ),
    ]
