# Generated by Django 3.1.5 on 2021-02-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_auto_20210224_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_desc',
        ),
    ]
