# Generated by Django 3.1.5 on 2021-01-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
