# Generated by Django 3.1.5 on 2021-01-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210114_0925'),
        ('carts', '0002_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='cart_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='product_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
