# Generated by Django 3.1.5 on 2021-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210115_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='date_created',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
    ]
