# Generated by Django 3.1.5 on 2021-01-27 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_cart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_per_cart', models.PositiveSmallIntegerField(default=5, verbose_name='Max Items Allowed per Cart (not used if zero)')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
