# Generated by Django 3.1.5 on 2021-01-28 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cartdefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdefault',
            name='max_per_cart',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Items Allowed per Cart'),
        ),
    ]
