# Generated by Django 3.1.5 on 2021-02-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20210128_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='product_price_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price Paid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='product_price_before_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Original Price'),
            preserve_default=False,
        ),
    ]
