# Generated by Django 3.1.5 on 2021-02-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210128_1053'),
        ('carts', '0010_auto_20210202_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
