# Generated by Django 3.1.5 on 2021-02-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_auto_20210202_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_sub_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Sub-Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_price_after_discount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Discounted Price'),
        ),
    ]
