# Generated by Django 3.1.5 on 2021-02-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_auto_20210202_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_items',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_ID',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_ID',
        ),
    ]
