# Generated by Django 3.1.5 on 2021-02-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_auto_20210203_0832'),
        ('orders', '0013_auto_20210203_0832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
