# Generated by Django 3.1.5 on 2021-02-16 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostageTypes',
            fields=[
                ('postage_id', models.CharField(choices=[('TK', 'Tracked'), ('SD', 'Standard')], max_length=2, primary_key=True, serialize=False, verbose_name='Postage Type')),
                ('postage_short_desc', models.CharField(max_length=255, verbose_name='Short Description of Postage Type')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region', models.CharField(choices=[('IE', 'Ireland & Northern Ireland'), ('GB', 'Great Britain'), ('EUR', 'Europe'), ('Z', 'Rest of the World')], default='Z', max_length=3, primary_key=True, serialize=False, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='PostageRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postage_type', models.CharField(choices=[('TK', 'Tracked'), ('SD', 'Standard')], max_length=2, verbose_name='Postage Type')),
                ('postage_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Postage Rate')),
                ('postage_rate_max_items', models.PositiveSmallIntegerField(default=5, verbose_name='Maximum number of items for Postage Rate')),
                ('postage_rate_per_extra_item', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Postage Rate per extra item')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.region', verbose_name='Postage Region')),
            ],
        ),
        migrations.CreateModel(
            name='CountryRegion',
            fields=[
                ('country_code', django_countries.fields.CountryField(max_length=2, primary_key=True, serialize=False, verbose_name='Country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.region', verbose_name='Region')),
            ],
        ),
    ]
