# Generated by Django 3.1.5 on 2021-02-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostageTypes',
            new_name='PostageType',
        ),
    ]
