# Generated by Django 3.1.5 on 2021-01-12 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity_ordered', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('customer_notes', models.TextField(verbose_name='Notes from Customer')),
                ('is_pending', models.BooleanField(default=False)),
                ('payment_succeeded', models.BooleanField(default=False)),
                ('payment_succeeded_date', models.DateTimeField(blank=True, null=True)),
                ('order_posted', models.BooleanField(default=False)),
                ('order_posted_date', models.DateTimeField(blank=True, null=True)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
        ),
    ]
