# Generated by Django 3.1.5 on 2021-01-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210113_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'STRIPE'), ('PayPal', 'PayPal')], default='STRIPE', max_length=6, verbose_name='Payment Method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_ref_from_method',
            field=models.CharField(default='dfsjfsdjsfkj2', max_length=255, verbose_name='Payment Method Reference ID'),
            preserve_default=False,
        ),
    ]
