# Generated by Django 3.1.5 on 2021-01-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210114_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_ref_from_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Method Reference ID'),
        ),
    ]
