# Generated by Django 3.1.5 on 2021-01-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210114_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address City'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address Country'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address Line1'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address Line2'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address Postal Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address State'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Phone'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address City'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Country'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line1'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Line2'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address Postal Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address State'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Phone'),
        ),
    ]
