# Generated by Django 3.1.5 on 2021-01-14 16:15

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210114_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Shipping Address Country'),
        ),
    ]
