# Generated by Django 3.1.5 on 2021-01-14 16:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210114_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address_country',
            field=django_countries.fields.CountryField(blank=True, max_length=255, null=True, verbose_name='Billing Address Country'),
        ),
    ]
