# Generated by Django 3.1.5 on 2021-01-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210128_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagerate',
            name='is_tracked',
        ),
        migrations.AddField(
            model_name='postagerate',
            name='postage_type',
            field=models.CharField(choices=[('TK', 'Tracked'), ('SD', 'Standard')], default='TK', max_length=2, verbose_name='Postage Type'),
            preserve_default=False,
        ),
    ]
