# Generated by Django 3.1.5 on 2021-02-02 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20210202_0914'),
        ('orders', '0011_auto_20210129_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_ID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_ID',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='carts.cart', verbose_name='Cart'),
            preserve_default=False,
        ),
    ]
