# Generated by Django 3.1.5 on 2021-02-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210128_1053'),
        ('orders', '0012_auto_20210202_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Discount Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_discount_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Order Discount Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Shipping Cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Sub-Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_ID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cart ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'STRIPE'), ('PayPal', 'PayPal'), ('Cash', 'Cash'), ('Free', 'Free')], max_length=6, verbose_name='Payment Method'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('product_discount_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Product Discount Code')),
                ('product_price_before_discount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Original Price')),
                ('product_price_after_discount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Discounted Price')),
                ('product_sub_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sub-Total')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(through='orders.OrderItem', to='products.Product'),
        ),
    ]
