# Generated by Django 3.1.5 on 2021-02-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210203_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
