# Generated by Django 3.1.5 on 2021-02-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_last_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_added',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_price_before_discount',
            new_name='product_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_price_after_discount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_discount_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Discount Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_final_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
