# Generated by Django 3.1.5 on 2021-02-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210203_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Shipping Type'),
        ),
    ]
