# Generated by Django 3.1.5 on 2021-02-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210203_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='order',
            name='order_complete',
            field=models.BooleanField(default=False, verbose_name='Order Complete?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes from Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_posted',
            field=models.BooleanField(default=False, verbose_name='Order has been posted?'),
        ),
    ]
