# Generated by Django 3.1.5 on 2021-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210203_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='order',
            name='final_total_from_cart',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total (from Cart)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Shipping Cost'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_final_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Original Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sub-Total'),
        ),
    ]
