# Generated by Django 3.1.5 on 2021-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20210203_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total_from_cart',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Subtotal (from Cart)'),
        ),
    ]
