# Generated by Django 3.1.5 on 2021-02-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_sub_total_from_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_succeeded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Payment Amount'),
        ),
    ]
