# Generated by Django 3.1.5 on 2021-02-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20210203_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_total_from_cart',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Shipping Cost (from Cart)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes from Customer/Order Notes'),
        ),
    ]
