# Generated by Django 3.1.5 on 2021-02-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_orderitem_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_sub_total',
        ),
    ]
