# Generated by Django 3.1.5 on 2021-02-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_orderitem_product_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_final_total',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
