# Generated by Django 3.1.5 on 2021-02-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_orderitem_product_price_for_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_order_confirmation_sent_to_customer',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Email Sent to Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_order_confirmation_sent_to_shop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Email Sent to Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_confirmation_sent_to_customer',
            field=models.BooleanField(default=False, verbose_name='Confirmation Email Sent to Customer?'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_confirmation_sent_to_shop',
            field=models.BooleanField(default=False, verbose_name='Order Email Sent to Shop?'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type_from_cart',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Type (from Cart)'),
        ),
    ]
