# Generated by Django 3.1.5 on 2021-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20210205_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_succeeded',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='PAID', max_length=12, verbose_name='Payment Status'),
            preserve_default=False,
        ),
    ]
