# Generated by Django 3.1.5 on 2021-02-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20210209_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_paypal_payer_id',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True, verbose_name='Payer ID (if PAYPAL)'),
        ),
    ]
