# Generated by Django 3.1.5 on 2021-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_billing_paypal_payer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_payment_failed_sent_to_customer',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Email Sent to Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_payment_failed_sent_to_shop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Email Sent to Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_failed_sent_to_customer',
            field=models.BooleanField(default=False, verbose_name='Payment Failed Email Sent to Customer?'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_failed_sent_to_shop',
            field=models.BooleanField(default=False, verbose_name='Payment Failed Email Sent to Shop?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED')], max_length=12, verbose_name='Payment Status'),
        ),
    ]
