# Generated by Django 3.1.5 on 2021-02-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20210215_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagerate',
            name='region',
        ),
        migrations.DeleteModel(
            name='CountryRegion',
        ),
        migrations.DeleteModel(
            name='PostageRate',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
