# Generated by Django 3.1.5 on 2021-03-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20210216_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_ref_from_refund',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Refund Reference ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Refund Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_refunded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'STRIPE'), ('PAYPAL', 'PayPal'), ('CASH', 'Cash'), ('FREE', 'FREE')], max_length=6, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('FREE', 'FREE'), ('REFUNDED', 'REFUNDED')], max_length=12, verbose_name='Payment Status'),
        ),
    ]
