# Generated by Django 3.1.5 on 2021-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_order_order_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_payment_refund_sent_to_customer',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Email Sent to Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_payment_refund_sent_to_shop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Email Sent to Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_refund_sent_to_customer',
            field=models.BooleanField(default=False, verbose_name='Payment Refund Email Sent to Customer?'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_refund_sent_to_shop',
            field=models.BooleanField(default=False, verbose_name='Payment Refund Email Sent to Shop?'),
        ),
    ]
