# Generated by Django 3.1.5 on 2021-01-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210112_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default='Sunglasses', max_length=255, verbose_name='Description of Product'),
            preserve_default=False,
        ),
    ]
