# Generated by Django 3.1.5 on 2021-01-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_sirv_1',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Product Image Sirv 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_sirv_1_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Image Sirv 1 Description'),
        ),
    ]
