# Generated by Django 3.1.5 on 2021-01-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210114_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_per_cart',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Max Allowed per Cart'),
        ),
    ]
