# Generated by Django 3.1.5 on 2021-01-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_max_per_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_per_cart',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Max Allowed per Cart (not used if zero)'),
        ),
    ]
