# Generated by Django 3.1.5 on 2021-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210127_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_per_cart',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Max Allowed per Order (not used if zero)'),
        ),
    ]
