# Generated by Django 3.1.5 on 2021-02-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210128_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_long_description',
            field=models.TextField(default='Enter the detailed description the customer will see on the Product page', verbose_name='Long Description of Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=255, verbose_name='Short Description of Product'),
        ),
    ]
