# Generated by Django 3.1.5 on 2021-02-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210218_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_sirv_5',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Product Image Sirv 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_sirv_5_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Image Sirv 5 Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_sirv_2_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Image Sirv 2 Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_sirv_3_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Image Sirv 3 Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_sirv_4_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Image Sirv 4 Description'),
        ),
    ]
